### ISSUE TITLE
Add docs for strategy explicit vs implicit

### ISSUE THREAD

**Issue by jrainville** [embark-framework/embark-site#166]

**Comment by PascalPrecht** [comment]
This has landed a while back.

**Comment by PascalPrecht** [comment]
https://embark.status.im/docs/contracts_configuration.html#Deployment-strategies

**Comment by NoahMarconi** [comment]
The docs are incorrect. 

Strategy  needs to be bumped back a line,

This:

```
strategy: 'explicit', // 'implicit' is the default
contracts: {
  SimpleStorage: {
    deploy: false
  },
  AnotherStorage: {
    ...
  }
}
```

instead of this:

```
contracts: {
  strategy: 'explicit' // 'implicit' is the default
  SimpleStorage: {
    deploy: false
  },
  AnotherStorage: {
    ...
  }
}
```

**Comment by jrainville** [comment]
Good catch!

I'll fix right away

**Comment by jrainville** [comment]
PR is here: https://github.com/embark-framework/embark/pull/1603

**Comment by NoahMarconi** [comment]
awesome!

**Comment by PascalPrecht** [comment]
This has landed as https://github.com/embark-framework/embark/commit/8781585341c40c8ecd9ea2177aa4274ad1d36a3e
